config/routes.rb
Rails.application.routes.draw do

  resources :articles
 root to: "home#index" 
 resources :jobs, only: [:index, :show]
 
 devise_for :job_seekers, controllers: 
 {
   sessions: 'job_seekers/sessions',
   registrations: 'job_seekers/registrations',
   passwords: 'job_seekers/passwords',
   confirmations: 'job_seekers/confirmations',
   unlocks: 'job_seekers/unlocks'
 }
 devise_for :employeers, controllers: 
 {
   sessions: 'employeers/sessions',
   registrations: 'employeers/registrations',
   passwords: 'employeers/passwords',
   confirmations: 'employeers/confirmations',

   unlocks: 'employeers/unlocks'
 }
 devise_for :admins, controllers: 
 {
   sessions: 'admins/sessions',
   registrations: 'admins/registrations',
   passwords: 'admins/passwords',
   confirmations: 'admins/confirmations',

   unlocks: 'admins/unlocks'
 }
 get '/browse-jobs-result' => "home#all_jobs"
 get'home/about'
 get'home/contact_us'
 get 'auths/auths'
  namespace :admin do 
    resources :jobs
    resources :job_categories
    resources :job_seekers
    resources :employeers
    resources :companies
    resources :articles
  end

  namespace :employeer do 
    get '/dashboard' => "dashboards#index"
    resources :jobs do 
      collection do 
        get :job_applicants
        get :applicant_details
        patch :application_status
      end
    end
    resources :companies
  end

  get '/apply-for-job' => "apply_job#register"
  post 'apply_job/create_job_registration'

  devise_scope :job_seeker do
  authenticated :job_seeker do
    root 'jobs#index', as: :authenticated_root
  end

  unauthenticated do
    root 'home#index', as: :unauthenticated_root
  end
end
end

app/models/job_category.rb
class JobCategory < ApplicationRecord
	has_many :jobs,dependent: :destroy
end

app/controllers/admin/job_categories_controller.rb
class Admin::JobCategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_job_category, only: [:show, :edit, :update, :destroy]

  # GET /job_categories
  # GET /job_categories.json
  def index
    @job_categories = JobCategory.all
  end

  # GET /job_categories/1
  # GET /job_categories/1.json
  def show
  end

  # GET /job_categories/new
  def new
    @job_category = JobCategory.new
  end

  # GET /job_categories/1/edit
  def edit
  end

  # POST /job_categories
  # POST /job_categories.json
  def create
    @job_category = JobCategory.new(job_category_params)

    respond_to do |format|
      if @job_category.save
        format.html { redirect_to admin_job_category_path(@job_category), notice: 'Job category was successfully created.' }
        format.json { render :show, status: :created, location: @job_category }
      else
        format.html { render :new }
        format.json { render json: @job_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_categories/1
  # PATCH/PUT /job_categories/1.json
  def update
    respond_to do |format|
      if @job_category.update(job_category_params)
        format.html { redirect_to admin_job_category_path(@job_category), notice: 'Job category was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_category }
      else
        format.html { render :edit }
        format.json { render json: @job_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_categories/1
  # DELETE /job_categories/1.json
  def destroy
    @job_category.destroy
    respond_to do |format|
      format.html { redirect_to admin_job_categories_url, notice: 'Job category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_category
      @job_category = JobCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_category_params
      params.require(:job_category).permit(:name, :icon_url, :description)
    end
end

app/helpers/job_categories_helper.rb
module JobCategoriesHelper
end

app/views/job_categories/_form.html.erb
<div class="card">
  <div class="card-body">
    <%= form_with(model: job_category, local: true) do |form| %>
      <% if job_category.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(job_category.errors.count, "error") %> prohibited this job_category from being saved:</h2>

          <ul>
          <% job_category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, id: :job_category_name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :icon_url %>
        <%= form.text_field :icon_url, id: :job_category_icon_url, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, id: :job_category_description, class: "form-control", rows: "5" %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
 </div>
</div>

app/views/job_categories/edit.html.erb
<h1>Editing Job Category</h1>

<%= render 'form', job_category: @job_category %>

<%= link_to 'Show', @job_category %> |
<%= link_to 'Back', job_categories_path %>

app/views/job_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Job Categories</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Icon url</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_categories.each do |job_category| %>
      <tr>
        <td><%= job_category.name %></td>
        <td><%= job_category.icon_url %></td>
        <td><%= job_category.description %></td>
        <td><%= link_to 'Show', job_category %></td>
        <td><%= link_to 'Edit', edit_job_category_path(job_category) %></td>
        <td><%= link_to 'Destroy', job_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Job Category', new_job_category_path %>

app/views/job_categories/new.html.erb
<h1>New Job Category</h1>

<%= render 'form', job_category: @job_category %>

<%= link_to 'Back', job_categories_path %>

app/views/job_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @job_category.name %>
</p>

<p>
  <strong>Icon url:</strong>
  <%= @job_category.icon_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job_category.description %>
</p>


<%= link_to 'Edit', edit_job_category_path(@job_category) %> |
<%= link_to 'Back', job_categories_path %>