config/routes.rb
Rails.application.routes.draw do

  resources :articles
 root to: "home#index" 
 resources :jobs, only: [:index, :show]
 
 devise_for :job_seekers, controllers: 
 {
   sessions: 'job_seekers/sessions',
   registrations: 'job_seekers/registrations',
   passwords: 'job_seekers/passwords',
   confirmations: 'job_seekers/confirmations',
   unlocks: 'job_seekers/unlocks'
 }
 devise_for :employeers, controllers: 
 {
   sessions: 'employeers/sessions',
   registrations: 'employeers/registrations',
   passwords: 'employeers/passwords',
   confirmations: 'employeers/confirmations',

   unlocks: 'employeers/unlocks'
 }
 devise_for :admins, controllers: 
 {
   sessions: 'admins/sessions',
   registrations: 'admins/registrations',
   passwords: 'admins/passwords',
   confirmations: 'admins/confirmations',

   unlocks: 'admins/unlocks'
 }
 get '/browse-jobs-result' => "home#all_jobs"
 get'home/about'
 get'home/contact_us'
 get 'auths/auths'
  namespace :admin do 
    resources :jobs
    resources :job_categories
    resources :job_seekers
    resources :employeers
    resources :companies
    resources :articles
  end

  namespace :employeer do 
    get '/dashboard' => "dashboards#index"
    resources :jobs do 
      collection do 
        get :job_applicants
        get :applicant_details
        patch :application_status
      end
    end
    resources :companies
  end

  get '/apply-for-job' => "apply_job#register"
  post 'apply_job/create_job_registration'

  devise_scope :job_seeker do
  authenticated :job_seeker do
    root 'jobs#index', as: :authenticated_root
  end

  unauthenticated do
    root 'home#index', as: :unauthenticated_root
  end
end
end

app/models/article.rb
class Article < ApplicationRecord
   mount_uploader :cover_image, ProfilePicUploader
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to admin_articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description, :cover_image)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @q = Article.ransack(params[:q])
  @articles = @q.result(distinct: true)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
  end

  # GET /articles/new
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_form.html.erb
<%= form_for ([:admin, @article]) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :article_title ,class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :article_description ,class:"ckeditor form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :cover_image %><br>
    <%= form.file_field :cover_image, id: :article_cover_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', admin_article_path {@article} %> |
<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/index.html.erb
<p id="notice"><%= notice %></p>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Cover image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.try(:description).try(:html_safe) %></td>
        <td><%= article.cover_image %></td>
        <td><%= link_to 'Show', admin_article_path(article) %></td>
        <td><%= link_to 'Edit', edit_admin_article_path(article) %></td>
        <td><%= link_to 'Destroy', admin_article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/admin/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.try(:description).try(:html_safe) %>
</p>

<p>
  <strong>Cover image:</strong>
  <%= image_tag @article.cover_image.url %>
</p>

<%= link_to 'Edit', edit_admin_article_path(@article) %> |
<%= link_to 'Back', admin_articles_path %>