config/routes.rb
Rails.application.routes.draw do

  resources :articles
 root to: "home#index" 
 resources :jobs, only: [:index, :show]
 
 devise_for :job_seekers, controllers: 
 {
   sessions: 'job_seekers/sessions',
   registrations: 'job_seekers/registrations',
   passwords: 'job_seekers/passwords',
   confirmations: 'job_seekers/confirmations',
   unlocks: 'job_seekers/unlocks'
 }
 devise_for :employeers, controllers: 
 {
   sessions: 'employeers/sessions',
   registrations: 'employeers/registrations',
   passwords: 'employeers/passwords',
   confirmations: 'employeers/confirmations',

   unlocks: 'employeers/unlocks'
 }
 devise_for :admins, controllers: 
 {
   sessions: 'admins/sessions',
   registrations: 'admins/registrations',
   passwords: 'admins/passwords',
   confirmations: 'admins/confirmations',

   unlocks: 'admins/unlocks'
 }
 get '/browse-jobs-result' => "home#all_jobs"
 get'home/about'
 get'home/contact_us'
 get 'auths/auths'
  namespace :admin do 
    resources :jobs
    resources :job_categories
    resources :job_seekers
    resources :employeers
    resources :companies
    resources :articles
  end

  namespace :employeer do 
    get '/dashboard' => "dashboards#index"
    resources :jobs do 
      collection do 
        get :job_applicants
        get :applicant_details
        patch :application_status
      end
    end
    resources :companies
  end

  get '/apply-for-job' => "apply_job#register"
  post 'apply_job/create_job_registration'

  devise_scope :job_seeker do
  authenticated :job_seeker do
    root 'jobs#index', as: :authenticated_root
  end

  unauthenticated do
    root 'home#index', as: :unauthenticated_root
  end
end
end

app/models/job.rb
class Job < ApplicationRecord

	paginates_per 5

	belongs_to :company,optional:true
	belongs_to :employeer,optional:true
	belongs_to :job_category,optional:true

  has_many :job_seeker_jobs
  has_many :job_seekers, through: :job_seeker_jobs

	geocoded_by :job_location
	after_validation :geocode

	def job_location
		"#{self.venue} #{self.city} #{self.state} #{self.country} #{self.zipcode}"
	end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  # before_action :authenticate_admin!, only: [:create, :new, :edit, :update, :destroy]
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to admin_job_path(@job), notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to admin_job_path(@job), notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to admin_jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit!
    end
end

app/controllers/employeer/jobs_controller.rb
class Employeer::JobsController < ApplicationController
  before_action :authenticate_employeer!, only: [:create, :new, :edit, :update, :destroy]
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  layout 'employeer'
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = current_employeer.jobs
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new 
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to employeer_job_path(@job), notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to employeer_job_path(@job), notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to employeer_jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def job_applicants
    @jobs = current_employeer.jobs
    @applicants = @jobs.map {|j| j.job_seeker_jobs }.flatten
  end

  def applicant_details
    @job_seeker = JobSeeker.find(params[:applicant_id])
    @job_seeker_job = JobSeekerJob.find(params[:job_seeker_job])
  end

  def application_status
    @job_seeker_job = JobSeekerJob.find(params[:job_seeker_job_id])
    if @job_seeker_job.update(job_application_status: params[:status])
      if params[:status] == "Accepted"
        @job_seeker_job.job.update(total_position: @job_seeker_job.job.total_position - 1)
        puts "Accepted"
      else
        @job_seeker_job.job.update(total_position: @job_seeker_job.job.total_position)
        puts "denied"
      end
      respond_to do |format|
        if @job_seeker_job.job_application_status == "Accepted"
          NotificationMailer.job_acceptance_notification_to_job_seeker(@job_seeker_job).deliver_now
        end
        format.html { redirect_to applicant_details_employeer_jobs_path(applicant_id: @job_seeker_job.job_seeker.id, job_seeker_job: @job_seeker_job.id), notice: "Application status has been updated successfully." }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit!
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # before_action :authenticate_job_seeker!, :only => [:show]
  def index
    @jobs = Job.all
  end
  def show
    @job = Job.find(params[:id])
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/admin/jobs/_form.html.erb
<div class="card">
  <div class="card-body">

<%= form_for([:admin, @job ]) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :job_category %>
    <%= form.select :job_category_id, options_for_select(JobCategory.all.collect{|jc| [jc.name, jc.id]}), {}, {id: :job_job_category, class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= form.label :job_title %>
    <%= form.text_field :job_title, id: :job_job_title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, id: :job_email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :job_type %>
    <%= form.text_field :job_type, id: :job_job_type , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :venue %>
    <%= form.text_field :venue, id: :job_venue , class: "form-control", id:"autocomplete",
     onFocus: "geolocate()"%>
  </div>

  <div class="form-group">
    <%= form.label :city %>
    <%= form.text_field :city, id: :job_city, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :state %>
    <%= form.text_field :state, id: :job_state, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :country %>
    <%= form.text_field :country, id: :job_country, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode, id: :job_zipcode, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :job_description %>
    <%= form.text_area :job_description, id: :job_job_description, rows: "5" , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :salary_range %>
    <%= form.text_field :salary_range, id: :job_salary_range, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :employeer_id %>
    <%= form.number_field :employeer_id, id: :job_employeer_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :company_id %>
    <%= form.number_field :company_id, id: :job_company_id , class: "form-control"%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>
</div>
 <script>
      // This example displays an address form, using the autocomplete feature
      // of the Google Places API to help users fill in the information.

      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      var placeSearch, autocomplete;
      var componentForm = {
        street_number: 'short_name',
        route: 'long_name',
        locality: 'long_name',
        administrative_area_level_1: 'short_name',
        country: 'long_name',
        postal_code: 'short_name'
      };

      function initAutocomplete() {
        // Create the autocomplete object, restricting the search to geographical
        // location types.
        autocomplete = new google.maps.places.Autocomplete(
            /** @type {!HTMLInputElement} */(document.getElementById('autocomplete')),
            {types: ['geocode']});

        // When the user selects an address from the dropdown, populate the address
        // fields in the form.
        autocomplete.addListener('place_changed', fillInAddress);
      }

      function fillInAddress() {
        // Get the place details from the autocomplete object.
        var place = autocomplete.getPlace();

        for (var component in componentForm) {
          document.getElementById(component).value = '';
          document.getElementById(component).disabled = false;
        }

        // Get each component of the address from the place details
        // and fill the corresponding field on the form.
        for (var i = 0; i < place.address_components.length; i++) {
          var addressType = place.address_components[i].types[0];
          if (componentForm[addressType]) {
            var val = place.address_components[i][componentForm[addressType]];
            document.getElementById(addressType).value = val;
          }
        }
      }

      // Bias the autocomplete object to the user's geographical location,
      // as supplied by the browser's 'navigator.geolocation' object.
      function geolocate() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var geolocation = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            var circle = new google.maps.Circle({
              center: geolocation,
              radius: position.coords.accuracy
            });
            autocomplete.setBounds(circle.getBounds());
          });
        }
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAfsqCxbcgsqYXMucH08nfifdtXK-8lPIQ&libraries=places&callback=initAutocomplete"
        async defer></script>
  </body

app/views/admin/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', admin_jobs_path %>

app/views/admin/jobs/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
<div class="text-center">
  <h1>Jobs</h1>
</div>

  <table class="table table-bordered" id="jobs">
    <thead>
      <tr>
        <th>Job title</th>
        <th>Email</th>
        <th>Job type</th>
        <th>Salary range</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @jobs.each do |job| %>
      <tr>
        <td><%= job.job_title %></td>
        <td><%= job.email %></td>
        <td><%= job.job_type %></td>
        <td><%= job.salary_range %></td>
        <td>  
          <%= link_to job, class: "btn btn-primary" do %>
            <i class="fa fa-eye"></i>View
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'New Job', new_admin_job_path %>
</div>

<br>

<script type="text/javascript">
  $(document).ready(function() {
    $('#jobs').DataTable();
  })
</script>

app/views/admin/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back' , admin_jobs_url %>

app/views/admin/jobs/show.html.erb
<div class="container">
  <div class="row" >
    <div class="col-md-7 col-sm-7">
      <div class="card">
        <div class="card-body">
          <h4 class="text-center card-title"><%= @job.job_title %></h4>
          <h5 class="job-headings">Job Description</h5>
          <p class="card-text job-values"><%= @job.job_description %></p>
          <h5 class="job-headings">Job Location</h5>
          <p class="card-text job-values"><i class="fa fa-map-marker"></i>  <%= @job.job_location %></p>
          <h5 class="job-headings">Email</h5>
          <p class="card-text job-values"><i class="fa fa-envelope"></i>  <%= @job.email %></p>
          <h5 class="job-headings">Salary Range</h5>
          <p class="card-text job-values"><i class="fa fa-inr"></i>  <%= @job.salary_range %></p>
          <h5 class="job-headings">Job type</h5>
          <p class="card-text job-values"><%= @job.job_type %></p>
          <p>
          </p>
         
          <%= link_to jobs_path, class: "btn btn-primary" do %>
            <i class="fa fa-arrow-left"></i> Back
          <% end %>

          <%= link_to new_job_seeker_session_path, class: "btn btn-primary" do %>
            <i class="fa fa-thumbs-up"></i> Apply Now
          <% end %>          

        </div>
      </div>
    </div>
    <div class="col-md-5 col-sm-5">
      <div id="map"></div>
    </div>
  </div>
</div>
<script>
  function initMap() {
    var job_location = {lat: <%= @job.latitude %>, lng: <%= @job.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 12,
      center: job_location
    });
    var marker = new google.maps.Marker({
      position: job_location,
      map: map
    });
  }
</script>
<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAfsqCxbcgsqYXMucH08nfifdtXK-8lPIQ&callback=initMap">
</script>