config/routes.rb
Rails.application.routes.draw do

  resources :articles
 root to: "home#index" 
 resources :jobs, only: [:index, :show]
 
 devise_for :job_seekers, controllers: 
 {
   sessions: 'job_seekers/sessions',
   registrations: 'job_seekers/registrations',
   passwords: 'job_seekers/passwords',
   confirmations: 'job_seekers/confirmations',
   unlocks: 'job_seekers/unlocks'
 }
 devise_for :employeers, controllers: 
 {
   sessions: 'employeers/sessions',
   registrations: 'employeers/registrations',
   passwords: 'employeers/passwords',
   confirmations: 'employeers/confirmations',

   unlocks: 'employeers/unlocks'
 }
 devise_for :admins, controllers: 
 {
   sessions: 'admins/sessions',
   registrations: 'admins/registrations',
   passwords: 'admins/passwords',
   confirmations: 'admins/confirmations',

   unlocks: 'admins/unlocks'
 }
 get '/browse-jobs-result' => "home#all_jobs"
 get'home/about'
 get'home/contact_us'
 get 'auths/auths'
  namespace :admin do 
    resources :jobs
    resources :job_categories
    resources :job_seekers
    resources :employeers
    resources :companies
    resources :articles
  end

  namespace :employeer do 
    get '/dashboard' => "dashboards#index"
    resources :jobs do 
      collection do 
        get :job_applicants
        get :applicant_details
        patch :application_status
      end
    end
    resources :companies
  end

  get '/apply-for-job' => "apply_job#register"
  post 'apply_job/create_job_registration'

  devise_scope :job_seeker do
  authenticated :job_seeker do
    root 'jobs#index', as: :authenticated_root
  end

  unauthenticated do
    root 'home#index', as: :unauthenticated_root
  end
end
end

app/models/company.rb
class Company < ApplicationRecord
	belongs_to :employeer,optional:true
end

app/models/employeer.rb
class Employeer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  paginates_per 5

  has_many :companies, dependent: :destroy
  has_many :jobs, dependent: :destroy

  mount_uploader :profile_pic, ProfilePicUploader

  def full_name
   	"#{self.first_name} #{self.last_name}"	
  end

  def full_address
    "#{self.address}, #{self.city}, #{self.state}, #{self.country}"
  end

end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to admin_company_path(@company), notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to admin_company_path(@company), notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to admin_companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :tagline, :description, :email, :contact, :website, :established_on, :staff_size, :address, :facebook_url, :twitter_url, :linkedin_url, :google_plus_url, :employeer_id)
    end
end

app/controllers/admin/employeers_controller.rb
class Admin::EmployeersController < ApplicationController
  # before_action :authenticate_admin!
  before_action :set_employeer, only: [:show, :edit, :update, :destroy]

  # GET /job_categories
  # GET /job_categories.json
  def index
    @employeers = Employeer.all
  end

  # GET /job_categories/1
  # GET /job_categories/1.json
  def show
  end

  # GET /job_categories/new
  def new
    @employeer = Employeer.new
  end

  # GET /job_categories/1/edit
  def edit
  end

  # POST /job_categories
  # POST /job_categories.json
  def create
    @employeer = Employeer.new(employeer_params)

    respond_to do |format|
      if @employeer.save
        format.html { redirect_to admin_employeer_path(@employeer), notice: 'Job category was successfully created.' }
        format.json { render :show, status: :created, location: @employeer }
      else
        format.html { render :new }
        format.json { render json: @employeer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_categories/1
  # PATCH/PUT /job_categories/1.json
  def update
    respond_to do |format|
      if @employeer.update(employeer_params)
        format.html { redirect_to admin_employeer_path(@employeer), notice: 'Job category was successfully updated.' }
        format.json { render :show, status: :ok, location: @employeer }
      else
        format.html { render :edit }
        format.json { render json: @employeer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_categories/1
  # DELETE /job_categories/1.json
  def destroy
    @employeer.destroy
    respond_to do |format|
      format.html { redirect_to admin_employeers_url, notice: 'Job category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employeer
      @employeer = Employeer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employeer_params
      params.require(:employeer).permit!
    end
end

app/controllers/employeer/companies_controller.rb
class Employeer::CompaniesController < ApplicationController
  before_action :authenticate_employeer!
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  layout 'employeer'
  # GET /companies
  # GET /companies.json
  def index
    @companies = current_employeer.companies
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to employeer_company_path(@company), notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to employeer_company_path(@company), notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to employeer_companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit!
    end
end

app/controllers/employeer/dashboards_controller.rb
class Employeer::DashboardsController < ApplicationController
  layout 'employeer'
  def index
  end

end

app/controllers/employeer/jobs_controller.rb
class Employeer::JobsController < ApplicationController
  before_action :authenticate_employeer!, only: [:create, :new, :edit, :update, :destroy]
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  layout 'employeer'
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = current_employeer.jobs
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new 
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to employeer_job_path(@job), notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to employeer_job_path(@job), notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to employeer_jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def job_applicants
    @jobs = current_employeer.jobs
    @applicants = @jobs.map {|j| j.job_seeker_jobs }.flatten
  end

  def applicant_details
    @job_seeker = JobSeeker.find(params[:applicant_id])
    @job_seeker_job = JobSeekerJob.find(params[:job_seeker_job])
  end

  def application_status
    @job_seeker_job = JobSeekerJob.find(params[:job_seeker_job_id])
    if @job_seeker_job.update(job_application_status: params[:status])
      if params[:status] == "Accepted"
        @job_seeker_job.job.update(total_position: @job_seeker_job.job.total_position - 1)
        puts "Accepted"
      else
        @job_seeker_job.job.update(total_position: @job_seeker_job.job.total_position)
        puts "denied"
      end
      respond_to do |format|
        if @job_seeker_job.job_application_status == "Accepted"
          NotificationMailer.job_acceptance_notification_to_job_seeker(@job_seeker_job).deliver_now
        end
        format.html { redirect_to applicant_details_employeer_jobs_path(applicant_id: @job_seeker_job.job_seeker.id, job_seeker_job: @job_seeker_job.id), notice: "Application status has been updated successfully." }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit!
    end
end

app/controllers/employeers/confirmations_controller.rb
# frozen_string_literal: true

class Employeers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/employeers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Employeers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/employeers/passwords_controller.rb
# frozen_string_literal: true

class Employeers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/employeers/registrations_controller.rb
# frozen_string_literal: true

class Employeers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]


  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    NotificationMailer.admin_notification(Admin.last).deliver_now
    NotificationMailer.employeer_notification(resource).deliver_now
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [::first_name,:last_name,:user_name])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
   new_employeer_job_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employeers/sessions_controller.rb
# frozen_string_literal: true

class Employeers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  # after_action :after_sign_in_path_for
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:first_name,:last_name,:user_name])
 end
  def after_sign_in_path_for(resource)
    new_employeer_job_path
  end
end

app/controllers/employeers/unlocks_controller.rb
# frozen_string_literal: true

class Employeers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/employeer/companies/_form.html.erb
<div class="card">
  <div class="card-header">
    <h3>New Company</h3>
  </div>
  <div class="card-body">  
    <%= form_for ([:employeer, @company]) do |form| %>
      <% if @company.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

          <ul>
          <% @company.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= form.hidden_field :employeer_id, id: :company_employeer_id, value: current_employeer.id, class: "form-control" %>

      <div class="row">
        <div class="col-sm col-md">
          <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, id: :company_name, class: "form-control" %>
          </div>
        </div>
        <div class="col-sm col-md">
          <div class="form-group">
            <%= form.label :tagline %>
            <%= form.text_field :tagline, id: :company_tagline, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm col-md">
          <div class="form-group">
            <%= form.label :email %>
            <%= form.text_field :email, id: :company_email, class: "form-control" %>
          </div>
        </div>
        <div class="col-sm col-md">
          <div class="form-group">
            <%= form.label :contact %>
            <%= form.text_field :contact, id: :company_contact, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm col-md">
          <div class="form-group">
            <%= form.label :website %>
            <%= form.text_field :website, id: :company_website, class: "form-control" %>
          </div>
        </div>
        <div class="col-sm col-md">
          <div class="form-group">
            <%= form.label :established_on %>
            <%= form.text_field :established_on, id: :company_established_on, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm col-md">
          <div class="form-group">
            <%= form.label :staff_size %>
            <%= form.text_field :staff_size, id: :company_staff_size, class: "form-control" %>
          </div>
        </div>
        <div class="col-sm col-md">
          <div class="form-group">
            <%= form.label :address %>
            <%= form.text_field :address, id: :company_address, class: "form-control" %>
          </div>
        </div>
      </div>

        
      <div class="row">
        <div class="col-sm col-md">
          <div class="form-group">
            <%= form.label :description %>
            <%= form.text_area :description, id: :company_description, class: "form-control ckeditor" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= form.submit class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>


<script type="text/javascript">
  $(".ckeditor").ckeditor();
</script>

app/views/employeer/companies/edit.html.erb
<div class="container">
  <div class="resource-form">
    <h1 class="mb-4 form-title-head"><i class="fa fa-pencil"></i>Editing Company </h1>
<%= render 'form', company: @company %>
<%= link_to 'Show', employeer_company_path(@company) %> |
<%= link_to 'Back', employeer_companies_path %>

app/views/employeer/companies/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Earn While Learn</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>
<div class="container">  
  <p id="notice"><%= notice %></p>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Contact</th>
        <th>Employeer</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @companies.each do |company| %>
        <tr>
          <td><%= company.name %></td>
          <td><%= company.email %></td>
          <td><%= company.contact %></td>
          <td><%= company.employeer.full_name %></td>
          <td>
            <%= link_to employeer_company_path(company),class:"btn btn-info" do %>
             <i class="fa fa-eye"></i> 
              <% end %>
            <%= link_to  edit_employeer_company_path(company),class:"btn btn-warning" do %>
            <i class="fa fa-pencil-square-o" ></i> 
              <% end %>
            <%= link_to  employeer_companies_path, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-danger" do%>
            <i class="fa fa-trash" ></i> 
             <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to new_employeer_company_path, class: "btn btn-primary" do %>
    <i class="fa fa-plus"></i> Add New Company
  <% end %>
</div>

app/views/employeer/companies/new.html.erb
<div class="jumbotron">
  <h1 class="display-6">Earn While Learn</h1>
  <p class="lead">Create jobs at Earn While Learn and hire well qualified people.</p>
  <hr class="my-4">
  <p class="lead">
    <%= link_to employeer_companies_path, class: "btn btn-primary btn-lg mb-4" do %>
      <i class="fa fa-arrow-left"></i> Back
    <% end %>
  </p>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-md-10 offset-md-1 offset-sm-1">
      <%= render 'form', company: @company %>
    </div>
  </div>
</div>

app/views/employeer/companies/show.html.erb
<div class="container">
  <div class="row" >
    <div class="col-md-7 col-sm-7">
      <div class="card">
        <div class="card-body">
          <p id="notice"><%= notice %></p>
          <h4 class="text-center card-title"><%= @company.name %></h4>
          <h5 class="job-headings">Company Description</h5>
          <p class="card-text job-values"><%= @company.try(:description).try(:html_safe) %></p>
  
          <h5 class="job-headings">Company Tagline</h5>
          <p class="card-text job-values"><i class="fa fa-quote-left"></i><%= @company.tagline %></p>

          <h5 class="job-headings">Email</h5>
          <p class="card-text job-values"><i class="fa fa-envelope"></i>  <%= @company.email %></p>

           <h5 class="job-headings">Contact</h5>
          <p class="card-text job-values"><i class="fa fa-phone"></i>  <%= @company.contact %></p>

           <h5 class="job-headings">Website</h5>
          <p class="card-text job-values"><i class="fa fa-globe"></i>  <%= @company.website %></p>
          <p>
            <strong>Established on:</strong>
           <p class="card-text job-values"><i class="fa fa-star" ></i><%= @company. established_on %></p>
          </p>

          <h5 class="job-headings">Staff Size</h5>
          <p class="card-text job-values"><%= @company. staff_size %></p>
           <h5 class="job-headings">Address</h5>
          <p class="card-text job-values"><i class="fa fa-address-book"></i>  <%= @company.address %></p>
         
         
            <h5 class="job-headings">Employeer</h5>
          <p class="card-text job-values"></i>  <%= @company.employeer_id %></p>
         
        </div>
      </div>
<%= link_to 'Edit', edit_employeer_company_path(@company) %> |
<%= link_to 'Back', employeer_companies_path %>
    </div>
  </div>
</div>